### PR TITLE
I add one CAN bus example for PRU 

### PR DESCRIPTION
**Pull request by zhanglongqi**
I add one CAN bus example for PRU,
the UART is debuging.
add more header files.
I have some release you can try

### CODE REVIEW

**Comment by texane** [comment]
Hi,

Thanks for the push request. Unfortunately, there are too much additionnal
contents and user specific things (see in the Makefiles ...). This complexifies
the repository, which I want to keep very simple for didactic purposes. Maybe
you could break your CAN example into a simplier, more contained, piece
of code and submit again ?

Thanks for you understanding,

**Comment by zhanglongqi** [comment]
The extra things are mainly can bus drivers and related headers from TI starterware, it have to be added,
it's complete now, include transmit, receive and filter, almost everything about the CAN bus.

**Comment by zhanglongqi** [comment]
I am sorry, there are so many other things there, I will reduce it later. Thanks for your advice

**Comment by texane** [comment]
Hi,

Thanks for your understanding, I want to keep this repository
as clean as possible. Please let me know when you reduced
the contents and resubmit again, the examples you sent are
good ones,

Cheers

2015-01-14 19:35 GMT-06:00 Zhang LongQi <notifications@github.com>:

**Pull request closed without merging**
